export type Style={code:string;title:string;description:string;image:string};
export type Product={id:string;slug:string;name:string;short:string;description:string;details:string[];gallery:Style[]};
const names:Record<string,string[]>= {
 brownies:['Classic Fudge','Walnut Crunch','Chocolate Chip','Brownie Gift Box','Salted Caramel','Double Chocolate','Hazelnut','White Chocolate Blondie','Berry Swirl','Brownie Bites'],
 bento:['Sweetheart Bento','Pastel Floral Bento','Chocolate Bento','Blue Birthday Bento','Vintage Piped Bento','Minimal Bento','Heart Bento','Mango Bento','Lavender Bento','Chocolate Ribbon Bento'],
 fondant:['Teddy Theme','Floral Celebration','Jungle Friends','Baby Shower','Safari Adventure','Unicorn Dream','Garden Elegance','Space Journey','Teddy Welcome','Pastel Castle'],
 bomboloni:['Vanilla Cloud','Chocolate Centre','Berry Cream','Assorted Box','Pistachio Cream','Nutella Centre','Strawberry Cream','Lemon Custard','Biscoff Cream','Party Assortment'],
 cupcakes:['Chocolate Swirl','Floral Buttercream','Red Velvet','Birthday Sprinkle','Pastel Rosette','Chocolate Ganache','Mango Delight','Cookies & Cream','Pastel Fantasy','Garden Floral'],
 donuts:['Chocolate Glaze','Strawberry Glaze','Cinnamon Sugar','Party Box','Dark Chocolate','Pistachio Glaze','Strawberry Sprinkle','Lotus Topping','Vanilla Sprinkle','Mini Donut Box'],
 birthday:['Chocolate Drip','White Floral','Pastel Birthday','Kids Celebration','Black Forest','Buttercream Bloom','Blue Minimal','Rainbow Party','Red Velvet','Golden Anniversary']
};
const styles=(slug:string,prefix:string)=>names[slug].map((title,i)=>({code:`${prefix}-${String(i+1).padStart(2,'0')}`,title,description:`${title} style — customise the flavour, egg preference and celebration details when you order.`,image:`/collections/${slug}/${slug}-${i+1}.jpg`}));
export const products:Product[]=[
 {id:'BRW-001',slug:'brownies',name:'Brownies',short:'Rich, fresh brownies made for sharing and gifting.',description:'Dessert(y) House brownies are baked to order for a deeply chocolatey, indulgent bite. Choose a style code below, your preferred quantity and egg or eggless option.',details:['Ten style references to choose from','Single portions, sharing boxes and gifting quantities','Egg or eggless option on request'],gallery:styles('brownies','BRW')},
 {id:'BEN-001',slug:'bento-cakes',name:'Bento Cakes',short:'Small celebration cakes with a big personal touch.',description:'Our bento cakes are made for intimate birthdays, date nights, surprises and little wins. Choose a style code and share your message, colour palette or inspiration.',details:['Ten personal-sized cake style references','Custom messages, colours and simple designs','Egg or eggless option on request'],gallery:styles('bento','BEN')},
 {id:'FON-001',slug:'fondant-cakes',name:'Fondant Cakes',short:'Handmade edible art for unforgettable celebrations.',description:'From delicate florals to playful themed designs, each fondant cake is made with hand-crafted details. Select a style code or share your own inspiration; book early for custom work.',details:['Ten fondant style references','Hand-modelled edible decorations','Advance booking required for custom work'],gallery:styles('fondant','FON')},
 {id:'BOM-001',slug:'bomboloni',name:'Bomboloni',short:'Soft filled doughnuts made for a joyful treat box.',description:'Fluffy bomboloni with creamy or chocolatey centres make a lovely add-on for parties, gifting and dessert tables. Select a style code and tell us your quantity.',details:['Ten filling and presentation references','Ideal for sharing boxes and celebrations','Freshly prepared for pre-orders'],gallery:styles('bomboloni','BOM')},
 {id:'CUP-001',slug:'cupcakes',name:'Cupcakes',short:'Fresh cupcakes for party tables and gifting.',description:'A box of cupcakes brings colour and joy to birthdays, school celebrations and return gifts. Choose a style code, flavour direction, theme and quantity.',details:['Ten cupcake style references','Buttercream colours and themed decoration','Egg or eggless option on request'],gallery:styles('cupcakes','CUP')},
 {id:'DON-001',slug:'donuts',name:'Donuts',short:'A cheerful selection for sharing and party tables.',description:'From classic sugar-dusted rings to colourful glazed donuts, these treats are a fun choice for gifting and gatherings. Select a style code and your preferred box size.',details:['Ten donut style references','Ideal for children’s parties and gifting','Prepared freshly for scheduled orders'],gallery:styles('donuts','DON')},
 {id:'BDY-001',slug:'birthday-cakes',name:'Birthday Cakes',short:'Made-to-order cakes for every age and milestone.',description:'Make the birthday table memorable with a cake designed around your celebration. Choose a style code, then share the serving count, flavour, colours and finishing details.',details:['Ten birthday-cake style references','Share serving count and theme for a tailored quote','Egg or eggless option on request'],gallery:styles('birthday','BDY')},
];
