import {NextRequest,NextResponse} from 'next/server';
import {v2 as cloudinary} from 'cloudinary';
import {createClient} from '@supabase/supabase-js';
export const runtime='nodejs';
const authorised=(r:NextRequest)=>r.headers.get('x-admin-password')===process.env.ADMIN_DASHBOARD_PASSWORD;
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
function media(){cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET,secure:true});return cloudinary}
export async function GET(r:NextRequest){if(!authorised(r))return NextResponse.json({error:'Unauthorised'},{status:401});const {data,error}=await db().from('posts').select('*').order('created_at',{ascending:false});return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({posts:data})}
export async function POST(r:NextRequest){if(!authorised(r))return NextResponse.json({error:'Unauthorised'},{status:401});try{const f=await r.formData(),file=f.get('image') as File|null,title=String(f.get('title')||''),description=String(f.get('description')||''),kind=String(f.get('kind')||'offer');if(!file||!title)return NextResponse.json({error:'Image and title are required.'},{status:400});if(file.size>8*1024*1024)return NextResponse.json({error:'Use an image below 8 MB.'},{status:400});const buf=Buffer.from(await file.arrayBuffer());const result=await new Promise<any>((resolve,reject)=>media().uploader.upload_stream({folder:'Desserty House/upcoming-posts',resource_type:'image',transformation:[{quality:'auto',fetch_format:'auto'}],context:{alt:title,caption:description}},(e,x)=>e?reject(e):resolve(x)).end(buf));const {data,error}=await db().from('posts').insert({title,description,kind,cloudinary_public_id:result.public_id,image_url:result.secure_url,is_published:true}).select().single();if(error){await media().uploader.destroy(result.public_id);throw error}return NextResponse.json({post:data})}catch(e){return NextResponse.json({error:'Upload failed. Check Cloudinary and database environment variables.'},{status:500})}}
export async function DELETE(r:NextRequest){if(!authorised(r))return NextResponse.json({error:'Unauthorised'},{status:401});const {id}=await r.json();const {data,error}=await db().from('posts').select('cloudinary_public_id').eq('id',id).single();if(error||!data)return NextResponse.json({error:'Post not found.'},{status:404});const result=await media().uploader.destroy(data.cloudinary_public_id,{resource_type:'image'});if(result.result!=='ok'&&result.result!=='not found')return NextResponse.json({error:'Cloudinary deletion failed. The website post was kept.'},{status:500});const removed=await db().from('posts').delete().eq('id',id);return removed.error?NextResponse.json({error:removed.error.message},{status:500}):NextResponse.json({ok:true})}
